jenkinsURLs:
  - https://ai-ci.amd.com/job/automations/job/entrypoints/job/github-psdb-entrypoint/
help:
  doc: https://confluence.amd.com/display/SI/PSDB+Jenkins+Trigger+-+GitHub+Guide
  enabled: false
  includeTriggers: false
  verbose: false
  message: This branch is configured to trigger PSDB. Comment __!help__ to get additional details
triggerExclusions:
  all:
    - "psdb-jenkins-trigger-dev[bot]"
    - "psdb-jenkins-trigger[bot]"
  onEdit:
    - "swjenci"
branches:
  - branchName: "amd-main"
    triggers:
      - triggerName: "!ai-review"
        description: Runs the AI Review job
        onOpen: false
        onSynchronize: false
        jobs:
          - "[jenkins-psdb, AI-Code-review/ai-code-review-psdb, queryFiles:summary-issues-clarity-aocl_compression]"
  - branchName: "amd/dev/sraut/ai-code-review-test"
    triggers:
      - triggerName: "!ai-review"
        description: Runs the AI Review job
        onOpen: true
        onSynchronize: true
        jobs:
          - "[jenkins-psdb, AI-Code-review/ai-code-review-psdb, queryFiles:summary-issues-clarity-aocl_compression]"
